version: '3'
services:
  frontend:
    image: ghcr.io/jeffhollan/grpc-sample-dotnet/https-frontend:${TAG}
    build:
      context: ./
      dockerfile: ./https-frontend/Dockerfile
    ports:
      - 8080:80
    environment:
      - GRPC_SERVER_ADDRESS
  backend:
    image: ghcr.io/jeffhollan/grpc-sample-dotnet/grpc-backend:${TAG}
    build:
      context: ./
      dockerfile: ./grpc-backend/Dockerfile
    ports:
      - 8081:5000